#cloud-config
# to protect https://docs.docker.com/engine/security/protect-access/

#packages:
#  # docker
#  - apt-transport-https
#  - ca-certificates
#  - curl
#  - gnupg
#  - lsb-release
#
groups:
  - docker

# добавляем GPG-ключ и репозиторий Docker
runcmd:
  # docker
  - mkdir -p /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
  - apt-get update -q
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
  - systemctl enable --now docker

write_files:
  # docker. enable tcp, use hub proxy
  - path: /etc/docker/daemon.json
    content: |
      { "hosts": ["unix:///var/run/docker.sock", "tcp://127.0.0.1:2375"], "registry-mirrors" : [ "https://dockerhub.timeweb.cloud" ] }
  - path: /etc/systemd/system/docker.service.d/override.conf
    content: |
      [Service]
      # дополнить/заменить параметры запуска
      # (systemd объединяет/перезаписывает по правилам)
      ExecStart=
      ExecStart=/usr/bin/dockerd --containerd=/run/containerd/containerd.sock

output: 
  all: '/var/log/cloud-init.log'
