---
version: '3.9'

services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:14
    container_name: wg-easy
    environment:
      - LANG=en
      - WG_HOST=${WG_HOST}
      - PASSWORD_HASH=${PASSWORD_HASH} # https://github.com/wg-easy/wg-easy/blob/v14.0.0/How_to_generate_an_bcrypt_hash.md
      - PORT=51828
      - WG_PORT=51827
      - UI_TRAFFIC_STATS=true
      - UI_CHART_TYPE=3 # (0 Charts disabled, 1 # Line chart, 2 # Area chart, 3 # Bar chart)
    volumes:
      - etc_wireguard:/etc/wireguard
    ports:
      - "51827:51827/udp"
      - "51828:51828/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped

volumes:
  etc_wireguard:
#  - iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
#  - iptables -P FORWARD ACCEPT
# systemd-detect-virt identify virtualization
